### ISSUE TITLE
Homepage visual redesign

### ISSUE THREAD

**Issue by sprestrelski** [acmucsd/acm-ai-site#134]
- [x] Update splash screen
![image](https://github.com/user-attachments/assets/0e3b681d-b098-4155-9f06-639415e5359b)

- [ ] Update team/wiki, remove more ACM section
![image](https://github.com/user-attachments/assets/303462d3-85ac-44ca-ae40-5535475802f4)
![image](https://github.com/user-attachments/assets/323ab65f-7926-4c94-83f8-ed0e48d66a10)

- [ ] Update apply knowledge section
![image](https://github.com/user-attachments/assets/4ad5e5ff-9c65-4b02-b962-ab97f47480e7)

- [ ] Remove Home button, add wiki button to navbar 

See Figma for more details.

**Comment by angelatsai1214** [comment]
Just linking the figma here 
https://www.figma.com/design/Z1R6tfoupX823JxZ4HJ08Z/ACM-AI-Website-Redesign?node-id=1039-295&node-type=CANVAS&t=Eh5BbYwLDmkjakEZ-0
