### ISSUE TITLE
[Long Term] - Jupyter Notebook Synced Workshop pages on Website

### ISSUE THREAD

**Issue by StoneT2000** [acmucsd/acm-ai-site#25]
Example:
https://d2l.ai/chapter_linear-networks/linear-regression.html#basic-elements-of-linear-regression

- Take jupyter notebook code from a workshop, port it to our website like documentation

**Comment by StoneT2000** [comment]
Comments:
Per WD: Precompile .ipynb files for now and upload to static site, have the static site then render it somewhere

**Comment by duanwilliam** [comment]
see [`acmucsd/acm-ai-workshops`](https://github.com/acmucsd/acm-ai-workshops/tree/main/website). the decision to colocate this section of the website with the workshops themselves was for ease of fetching workshop data, but it should be able to be flexible through use of git submodules if necessary.
the workshops are viewable at https://wiki.ai.acmucsd.com
