### ISSUE TITLE
Add link to wiki page to main website

### ISSUE THREAD

**Issue by StoneT2000** [acmucsd/acm-ai-site#51]
Add a link to wiki.ai.acmucsd.com. We would like to have one on the header component at least. On the events page, we should also add that to the "Where to find our workshops?" section.

**Comment by alvyynm** [comment]
Hey, @StoneT2000, I can help with this. Any specifics you'd like for the events section?

**Comment by StoneT2000** [comment]
You certainly can, although this repo isn't really a good open source project (it's basically internally maintained).

**Comment by alvyynm** [comment]
Noted, thank you @StoneT2000
