### ISSUE TITLE
Fix card overflow on events card 

### ISSUE THREAD

**Issue by StoneT2000** [acmucsd/acm-ai-site#52]
Our events card has some strange border, we would like to fix the CSS for that.
<img width="1158" alt="Screen Shot 2022-09-27 at 12 16 36 PM" src="https://user-images.githubusercontent.com/35373228/192615953-2667d5cc-9bdf-46b7-b1ec-68dfbc687451.png">

**Comment by sprestrelski** [comment]
Events card was redesigned with 2.0 version, no longer an issue
