### ISSUE TITLE
Submission details page

### ISSUE THREAD

**Issue by StoneT2000** [acmucsd/acm-ai-site#80]
/competitions/:comp_name/teams/:team_name/submissions/:submission_id

This should be a general submissions page for this particular team

Use this API route /:competitionName/entry/:submissionId to find all matches from this submission

Display the raw data for now.

Also need a button on /competitions/:comp_name/teams/:team_name/ page to click to go to submission page (with a back button to the team page)./

**Comment by CatFish47** [comment]
PR #82
